language: cpp
compiler:
    - gcc
    - clang

env:
    - CXXFLAGS='-std=c++11'
    - CXXFLAGS='-std=c++14'
    - CXXFLAGS='-std=c++17'

os: linux
dist: xenial

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libstdc++-8-dev

before_script:
    - echo Hello

script:
    - make test

jobs:
    include:
        - stage: report coverage
          compiler: clang
          env: CXXFLAGS='-std=c++17'
          script:
              - export CXX=clang++
              - export CXXFLAGS="-fprofile-instr-generate -fcoverage-mapping -g"
              - make test
              - llvm-profdata merge default.profraw -output=default.profdata
              - llvm-cov show test/test -instr-profile=default.profdata > coverage.txt
              - bash <(curl -s https://codecov.io/bash)
