language: cpp
compiler:
    - gcc
    - clang

env:
    - CXXFLAGS='-std=c++11 --coverage'
    - CXXFLAGS='-std=c++14 --coverage'
    - CXXFLAGS='-std=c++17 --coverage'

os: linux
dist: xenial

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libstdc++-8-dev

before_install:
    - cd test

install:
    - make clean
    - make build

script:
    - make run
